import Head from 'next/head'
import { useContext, useEffect, useState } from 'react'
import AuthContext from '../context/AuthContext'
import Router from 'next/router'
import Sidebar from '../components/Sidebar'
import ChatBox from '../components/ChatBox'
import { AvatarIcon, ChatsIcon, MenuIcon, SearchIcon } from '../components/Icons'
// import styles from '../styles/Home.module.css'


export default function Home() {
  const { isAuthenticated } = useContext(AuthContext)
  const [isChatbox, setIsChatbox] = useState()

  useEffect(() => {
    console.log("is auth", isAuthenticated)
    if (!isAuthenticated) {
      Router.push('/login')
    }
  }, [isAuthenticated])


  return (
    <>
      <Head>
        <title>React Chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className='flex-row md:flex full-app'>
          <div>
            {/* app header */}
            <div className='flex w-screen md:w-auto border-b justify-between z-40 px-2 items-center h-14 bg-[#343A46] shadow-lg'>
              <div className='hover:opacity-60'>
                <AvatarIcon />
              </div>
              <div>
                {/* <p className='font-semibold'>{userData?.email ? userData.email : ''}</p> */}
                <p className='font-semibold'>Whatsapp Clone</p>
              </div>
              <div className='flex space-x-2'>
                <div onClick={() => setIsChatbox(!isChatbox)} className='hover:opacity-60'>
                  <ChatsIcon className="bg-black" />
                </div>
                <div className='hover:opacity-60'>
                  <MenuIcon />
                </div>
              </div>
            </div>

            <div className={`absolute top-0 z-50 md:z-40 md:block md:static ${isChatbox ? 'block' : 'hidden'} `}>
              <Sidebar />
              <div onClick={() => setIsChatbox(!isChatbox)} className='absolute bottom-5 left-4'>
                <button className='px-6 md:hidden py-2 rounded-md bg-[#16181D]'>Close</button>
              </div>
            </div>
          </div>

          <ChatBox />
        </div>
      </div>
    </>
  )
}
