import Head from 'next/head'
import { useContext, useEffect } from 'react'
import AuthContext from '../context/AuthContext'
import Router from 'next/router'
import Sidebar from '../components/Sidebar'
import Contacts from '../components/Contacts'
import ChatBox from '../components/ChatBox'
// import styles from '../styles/Home.module.css'


export default function Home() {
  const { isAuthenticated, getUserData, signOut, userData } = useContext(AuthContext)
  useEffect(() => {
    console.log("is auth", isAuthenticated)
    if (!isAuthenticated) {
      getUserData
      Router.push('/login')
    }
  }, [isAuthenticated])


  return (
    <>
      <Head>
        <title>Whatsapp - chat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className='full-app overflow-hidden'>
          <Sidebar />
          <ChatBox chatId={23} />
        </div>
      </div>
    </>
  )
}
